# Generated by Django 3.0.5 on 2020-08-24 06:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20200822_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='AHtml',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Editable detail'),
        ),
        migrations.AddField(
            model_name='news',
            name='NHtml',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Editable detail'),
        ),
        migrations.AddField(
            model_name='success',
            name='SHtml',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Editable detail'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='ADate',
            field=models.DateTimeField(verbose_name='Adds Date'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='ADetail',
            field=models.TextField(blank=True, null=True, verbose_name='default Detail'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='AImage',
            field=models.ImageField(blank=True, null=True, upload_to='adds/', verbose_name='Adds Image'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='ATitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adds Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CAddress',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CEmail',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CFacebook',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CPhone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CTelegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CTwitter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='motionimage',
            name='MIDetail',
            field=models.TextField(blank=True, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='motionimage',
            name='MIImage',
            field=models.ImageField(blank=True, null=True, upload_to='motion/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='motionimage',
            name='MIRelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.NavBar', verbose_name='Dedicated to'),
        ),
        migrations.AlterField(
            model_name='motionimage',
            name='MITitle',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='motionimage',
            name='MIVisible',
            field=models.BooleanField(verbose_name="it's visible?"),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='NAVHasFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.NavBar', verbose_name='Has Father?'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='NAVHtml',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content HTML'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='NAVName',
            field=models.CharField(max_length=50, verbose_name='Navbar Title'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='NAVSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NDate',
            field=models.DateTimeField(verbose_name='news Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NDetail',
            field=models.TextField(blank=True, null=True, verbose_name='default detail'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NImage',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='news Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NShort',
            field=models.TextField(blank=True, null=True, verbose_name='news short'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NTitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='News Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QAnswer',
            field=models.TextField(blank=True, null=True, verbose_name='The answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QQuestion',
            field=models.CharField(max_length=100, verbose_name='The question'),
        ),
        migrations.AlterField(
            model_name='success',
            name='SDep',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='success',
            name='SDetail',
            field=models.TextField(blank=True, null=True, verbose_name='default detail'),
        ),
        migrations.AlterField(
            model_name='success',
            name='SImage',
            field=models.ImageField(blank=True, null=True, upload_to='success/', verbose_name='primary Image'),
        ),
        migrations.AlterField(
            model_name='success',
            name='STitle',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
