# Generated by Django 3.0.7 on 2020-08-26 19:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_auto_20200824_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('DCareer', models.CharField(max_length=100, verbose_name='Doctor career')),
                ('DAbout', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Editable about')),
                ('DImage', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='primary Image')),
                ('DFacebook', models.CharField(max_length=150, verbose_name='Facebook')),
                ('DLinkedin', models.CharField(max_length=150, verbose_name='Linked in')),
                ('DTwitter', models.CharField(max_length=150, verbose_name='Twitter')),
            ],
        ),
    ]
