# Generated by Django 3.1.1 on 2020-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_adds_apdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='APDF',
            field=models.FileField(blank=True, null=True, upload_to='news/files/'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='APDF',
            field=models.FileField(blank=True, null=True, upload_to='adds/files/'),
        ),
    ]
