# Generated by Django 3.1.1 on 2020-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_auto_20200930_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adds',
            name='APDF',
        ),
        migrations.RemoveField(
            model_name='news',
            name='APDF',
        ),
        migrations.AddField(
            model_name='adds',
            name='APdf',
            field=models.FileField(blank=True, null=True, upload_to='adds/files/', verbose_name='File Upload'),
        ),
        migrations.AddField(
            model_name='news',
            name='NPdf',
            field=models.FileField(blank=True, null=True, upload_to='news/files/', verbose_name='File Upload'),
        ),
    ]
