# Generated by Django 3.1.1 on 2020-10-03 19:15

from django.db import migrations, models
import structure.validators


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_success_svideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='APdf',
            field=models.FileField(blank=True, null=True, upload_to='adds/files/', validators=[structure.validators.validate_pdf_file], verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NPdf',
            field=models.FileField(blank=True, null=True, upload_to='news/files/', validators=[structure.validators.validate_pdf_file], verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='success',
            name='SVideo',
            field=models.FileField(blank=True, null=True, upload_to='success/videos/', validators=[structure.validators.validate_video_file], verbose_name='Video upload'),
        ),
    ]
