# Generated by Django 3.1.1 on 2020-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='CTwitter',
        ),
        migrations.AddField(
            model_name='contact',
            name='CYoutube',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='YouTube'),
        ),
    ]
